CREATE TABLE generated_content (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  site_url TEXT UNIQUE NOT NULL,
  content JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);